-- 코드를 입력하세요
-- 테이블 2개 : ANIMAL_INS, ANIMAL_OUTS
-- 겹치는 컬럼은 ANIMAL_ID, ANIMAL_TYPE, NAME (속성도같음)
-- 찾아야 할 것 , 입양 간 기록은 있음 (OUTS O) 보호소에 들어온 기록은 없음 (INS X)
-- 

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_OUTS.ANIMAL_ID;