SELECT 
    E.TITLE,
    E.BOARD_ID,  
    E2.REPLY_ID, 
    E2.WRITER_ID AS REPLY_WRITER_ID, 
    E2.CONTENTS, 
    TO_CHAR(E2.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD E
    INNER JOIN USED_GOODS_REPLY E2
        ON E.BOARD_ID = E2.BOARD_ID
WHERE 
    TO_CHAR(E.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY 
    E2.CREATED_DATE ASC, 
    E.TITLE ASC;
